@startuml
start
:registriereSpieler;
if(spieler bekannt) then (Ja);
    :lade letzten spielstand;
    if(spielstand valide) then (Ja);
        :baue neue Reihenfolge
        aus geladenem Spielstand;
        :gebe neue
        Reihenfolge zurück;
        end
    endif
endif
:gebe bisherige
Reihenfolge Zurück;
end
@enduml