@startuml
start
:Akzeptiere Socket;
if (Namensprüfung aktiv) then (Ja)
    :Initialisiere
    Kommunikationskanäle;
    :Empfange Spielername;
    if (Spielername vorhanden) then (Ja)
        :Sende DISCONNECT Signal;
        :Schließe Client;
    else (Nein)
        :Sende CONNECT Signal;
        :Merke Spielernamen;
    endif
endif
if (Füge Spieler hinzu) then (Ja)
    :Initialisiere
    ClientHandler;
endif;
end
@enduml