@startuml
start
:initialisiere Logger nach Namen;
:Setze Loglevel aus Konfig;
if (Logger hat Handler) then (Nein)
    :Füge neuen ConsoleHandler hinzu;
    :Setze Loglevel aus Konfig;
endif
:Gebe Logger zurück;
end
@enduml