@startuml
start
:lege neue leere List an;
while(nicht alle Karten gespielt)
   :sende Kommande;
   :empfange Karte;
   :füge Karte zur Liste hinzu;
   :ermittle Stich;
   :sende Stich Ergebnis;
endwhile
:speichere Liste;
end
@enduml