@startuml
start
repeat
if (botSpawnerRunning) then (true)

else (false)
  :spawnBots();
  :botSpawnerRunning = true;
  :execute BotSpawner-Runnable;
  fork
  	partition "BotSpawner" {
  	:startTime = System.currentTimeMillis();
  	repeat
  	    if(yoolooServer.getClientCount() < minRealPlayers)
                :startTime = System.currentTimeMillis();
                :sleep(3000);
                :continue;
        endif
  	    if (botSpawnCriteriaOk) then
  	        partition "spawn (neededPlayers - curPlayerCount) bots" {
  	        fork
  	            :start new YoolooClient;
  	        fork again
                :start new Yoo...;
            fork again
                :...;
  	        end fork
  	        }
  	        : interrupt current Thread;
  	        end
  	    endif
  	  :sleep(1000);
  	  repeat while (yoolooServer.getClientCount() < yoolooServer.getSpielerProRunde())
  	  }
  end fork
  endif
  :...;
repeat while (serverActive)
end
@enduml